### ISSUE TITLE
Determine hosting provider and details

### ISSUE THREAD

**Issue by Nedlinin** [martijnboers/BlotterTrax#1]
Need to determine how we are intending to host the bot.

Hosting provider: Amazon EC2 Micro?  Digital Ocean?
Organize login methods for @martijnboers and @Nedlinin for maintenance needs.

Continuous deployment?  Docker container desired?

**Comment by martijnboers** [comment]
I want to try out Github actions to setup CD. Will report back with best provider

**Comment by Nedlinin** [comment]
I'm unfamiliar with Github Actions (I typically use Bamboo).  I think it's a freebie these days though so it's definitely worth learning 👍

**Comment by Nedlinin** [comment]
As mentioned on Discord, I setup an EC2 instance for the time being so we can ensure its ran on the cloud in a place we can both get to.  Login details sent there.

Looks like a large chunk of the docker work has been tackled by you on another branch.  Any status update there?

**Comment by martijnboers** [comment]
You're right, I will create the PR

**Comment by Nedlinin** [comment]
Closing this issue as EC2 appears to be working out for the time being.
