### ISSUE TITLE
It possible that double > can end up in the artist bio post

### ISSUE THREAD

**Issue by martijnboers** [martijnboers/BlotterTrax#19]
See: https://www.reddit.com/r/listentothis/comments/f65cxl/mischief_brew_olde_tyme_memry_folk_2016/fi4q7up/?context=3

This could possibly be cause by a double newline character as they get filtered out here

https://github.com/martijnboers/BlotterTrax/blob/1331c7608e9d693d3d789a7fec9660b94d956f0c/lastfm.py#L51-L52

**Comment by TcMaX** [comment]
I can't see the comment so I don't understand the problem, but a double newline shouldnt cause that issue. In my experience \n>\n> will correctly be identified as a new paragraph in the quote by reddit. Any chance I could have a screenshot of the comment?

**Comment by martijnboers** [comment]
Artist: https://www.last.fm/music/Mischief+Brew

![image](https://user-images.githubusercontent.com/2955898/74919706-49368e00-53cb-11ea-801d-916c4485306f.png)

**Comment by TcMaX** [comment]
This looks like it could be a code block? that would be caused by a series of spaces in the beginning of the line (at least 4)
I am almost certain it is not a nested quote, though I don't know new reddit

**Comment by Nedlinin** [comment]
You might be right there.

In which case simply


re.sub('\s+',' ' text)

Should be enough to fix this one.

Thanks,
Chris Heath
--

**Comment by TcMaX** [comment]
hm i did some more testing and im not quite sure, I dont think its possible to have code block in quote?

Could someone with access do a getSubmission request on the comment and get the raw body data from the api?

**Comment by Nedlinin** [comment]
The summary is:


` "Mischief Brew was an anarchist folk-punk band. A wicked concoction by Erik Petersen – a musical feast falling somewhere between the categories of pirate punk, Celtic folk, gypsy swing, devilish jazz, American olde-tyme and country. It’s good music to stomp, kick, pogo, jitterbug, waltz, drink, twist and shout to – whether the performance is solo acoustic or with a backing band of accordion, drums, and mandolin.\n\n            Erik started making music at a young age <a href=\"https://www.last.fm/music/Mischief+Brew\">Read more on Last.fm</a>"`

Github doesn't format this properly either but the key piece is that the \n\n is followed by 12 spaces.

Perhaps we run it through

`re.sub("\n+", "\n>", re.sub('\s+',' ', description))`

I think that'll clobber both the extra lines (replacing them with a single quote for our need) as well as stripping excess spaces from the text body.

**Comment by TcMaX** [comment]
using native split function, then strip and join also can. It's not going to get rid of mid-text double space, but it will handle the main issue and should be faster than regex

**Comment by Nedlinin** [comment]
@TcMaX : I think that would remove newlines as well though wouldn't it?

**Comment by TcMaX** [comment]
Nono I mean split into list, strip the strings in it, then join the list with separator newline (and quote sign I suppose).

Though by all means dropping newlines alltogether is also an option

**Comment by TcMaX** [comment]
So something like

`summarySplit = summary.split('\n')
strippedList = list(map(str.strip, summarySplit))
newSummary = '\n>'.join(strippedList)`

Completely untested, but something in this ballpark. I think it'd be a fair bit faster than regex

**Comment by TcMaX** [comment]
![image](https://user-images.githubusercontent.com/8627391/74975540-302cec00-5462-11ea-8305-420cbb7c68dc.png)
seems to work. obviously first one no quote but thats easy fix
