### ISSUE TITLE
_extract_artist_post_title can match on artist name itself

### ISSUE THREAD

**Issue by Nedlinin** [martijnboers/BlotterTrax#3]
The function _extract_artist_post_title currently matches based on " -" appearing in the post title.  However, this could be within the artist name itself.  Look into making this function more robust in the hopes of not hitting false matches.

/r/listentothis currently states there is to be double dashes in the title but experience tells me many users do *not* follow this and use a single dash so we can't necessarily rely on that.

https://www.reddit.com/r/listentothis/wiki/rules#wiki_title_format.3A_artistname_--_trackname_.5Bgenre_.2F_genres.5D_.28year.29

**Comment by martijnboers** [comment]
I would say drop the double dash requirements as only 30% of new submissions known about this rule. I'd rather look at where it goes wrong and adjust regex based on that
