### ISSUE TITLE
Further expand artist/song title extraction

### ISSUE THREAD

**Issue by Nedlinin** [martijnboers/BlotterTrax#39]
Found some small issues with artist/song title tests that we might want to try to find a way to pass.

>             ('007Bonez feat Adro - Motion [Hip-Hop / Rap] (2019)', '007Bonez feat Adro', None, 'Motion'),

This should be

>            ('007Bonez feat Adro - Motion [Hip-Hop / Rap] (2019)', '007Bonez', 'Adro', 'Motion'),

But, worse yet, artists that actually have & in the name are detected as a featured artist.  For example:

>            'Simon & Garfunkel - The Sound of Silence'

Would list the main artist as Simon and the featured artist as Garfunkel.

Not sure there will be an easy way to solve that second one though.

**Comment by TcMaX** [comment]
Both of these are unfortunately unsolvable problems, we will have to consider which is the better mistake to make based on seriousness and frequency of occurence in each of the ways they can occur. I do believe adding the additional check for feat is probably worth, idk which is the better option for &

**Comment by martijnboers** [comment]
Stumbled on this while searching online for possible solutions: 

https://stackoverflow.com/questions/56084573/parsing-a-song-title-from-r-listentothis-for-an-ifttt-applet

**Comment by TcMaX** [comment]
> Stumbled on this while searching online for possible solutions:
> 
> https://stackoverflow.com/questions/56084573/parsing-a-song-title-from-r-listentothis-for-an-ifttt-applet

We already have that mostly implemented in the repost PR, from what I can tell it is far more comprehensive than the answers on that stackoverflow, though if there is any specific case feel free to leave a comment on #14

**Comment by Nedlinin** [comment]
Lots of this was solved in #48 .


some more current failures:

`
            ('Floating Points feat. Testing--Last Bloom ', 'Floating Points', 'Testing', 'last bloom'),
`

**Comment by TcMaX** [comment]
I think this should be closed now as it seems to be solved to the degree that is reasonably possible. If there are future issues with artist/song title extraction we should have a new issue for it
