### ISSUE TITLE
Properly label social networks in the description reply

### ISSUE THREAD

**Issue by Nedlinin** [martijnboers/BlotterTrax#61]
https://www.reddit.com/r/listentothis/comments/frnzfw/squid_sludge_experimental_rock_2020/flwrnku/

This contains 

> socials: bandcamp, discogs, free streaming, purchase for download, social network, social network, social network, soundcloud

as the reply.  Should be fairly trivial to check the URL for containing facebook, twitter, instagram, etc and replace the text with the actual social network being linked to rather than forcing the user to click/hover each.

**Comment by martijnboers** [comment]
Closed by https://github.com/martijnboers/BlotterTrax/pull/63
