### ISSUE TITLE
Ensure description gets sanitized for markdown formatting

### ISSUE THREAD

**Issue by Nedlinin** [martijnboers/BlotterTrax#62]
https://www.reddit.com/r/listentothis/comments/frhf3e/caravan_golf_girl_progressive_rock_1971/flvs3pr/

Ends up with the following contained in it's markdown:

` [wikipedia](https://en.wikipedia.org/wiki/Caravan_(band))`

When it reality it needs to be

` [wikipedia](https://en.wikipedia.org/wiki/Caravan_(band\))`

We should probably escape any closing parens contained within links so that reddit will properly parse the URL.

**Comment by martijnboers** [comment]
Actually both parentheses needed to be escaped

**Comment by martijnboers** [comment]
Closed by https://github.com/martijnboers/BlotterTrax/pull/63
