### ISSUE TITLE
Send report instead of deleting submisions

### ISSUE THREAD

**Issue by martijnboers** [martijnboers/BlotterTrax#7]
A requirement to test the bot is that as a first step it should send modmail instead of deleting submissions when they exceed the threshold.

Should it also not reply with the artist bio?

**Comment by Nedlinin** [comment]
To clarify, instead of sending mod mail it can simply report the post with a reason similar to "BlotterTrax suggests a mod check out this point for exceeding limits.  <Service Name>: <Service Count>"

**Comment by Nedlinin** [comment]
wrt; bio, I think go ahead and post it though I think we need to ensure it only gets stickied if we actually found an artist.
