### ISSUE TITLE
Use SoundCloud service to enforce rules

### ISSUE THREAD

**Issue by martijnboers** [martijnboers/BlotterTrax#8]
Looking at new posts in `/r/listentothis` I see a lot of SoundCloud links, would be nice if this service is also implemented and can be used to enforced the rules

**Comment by TcMaX** [comment]
I've mostly wrapped my head around this API I think, I'll try to implement this over the next day or two. Though, I'm not sure how useful it will be, it seems quite rare for soundcloud entries to break the rules

**Comment by martijnboers** [comment]
Done in https://github.com/martijnboers/BlotterTrax/pull/22, closing
